/**
 * Sitemap generation (Task 55; architecture §7 "Per-language sitemaps
 * with `lastmod`... regenerated by `jobs`"). `jobs/regen-sitemaps.ts`
 * runs `regenerateSitemaps` hourly.
 *
 * MINIMAL — Task 60 expands this to full ward/candidate coverage (369
 * wards + every candidate route, EN and KN, with real `lastmod` from
 * publish timestamps). This first cut covers only the small, fixed set
 * of top-level static public routes that exist today, so the hourly job
 * has something real and correct to run from day one rather than an
 * empty stub or a job that doesn't exist yet.
 *
 * EXCLUDED (matches architecture §7's "noindex and sitemap exclusion"
 * list verbatim): `/partner/{slug}` (unlisted), `/account/*`,
 * `/curator/*`, `/admin/*`, `/login`.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { localePath, type Lang } from '../../i18n';

/**
 * Root-relative, EN-canonical paths — same convention as Base.astro's
 * `path` prop (never `/kn`-prefixed; `localePath` derives the KN twin).
 * Every one of these is a real static top-level page with a KN twin under
 * src/pages/kn/ as of Task 55.
 */
export const STATIC_ROUTES: string[] = [
  '/',
  '/about',
  '/about-election',
  '/check-registration',
  '/data',
  '/partner-with-us',
  '/press',
  '/privacy',
  '/terms',
  '/voting-guide',
  '/voting-guide/how-to-vote',
  '/voting-guide/voter-id',
  '/voting-guide/find-booth',
];

/** Same fallback convention as astro.config.mjs / src/lib/send/calendar.ts. */
const SITE_ORIGIN = process.env.SITE_ORIGIN ?? 'https://bangalore-votes.opencity.in';

function buildUrlSet(lang: Lang, lastmod: string): string {
  const urls = STATIC_ROUTES.map((route) => {
    const loc = new URL(localePath(lang, route), SITE_ORIGIN).href;
    return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
  }).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function buildSitemapIndex(lastmod: string): string {
  const enLoc = new URL('/sitemap-en.xml', SITE_ORIGIN).href;
  const knLoc = new URL('/sitemap-kn.xml', SITE_ORIGIN).href;
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `  <sitemap>\n    <loc>${enLoc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>\n` +
    `  <sitemap>\n    <loc>${knLoc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>\n` +
    `</sitemapindex>\n`
  );
}

export interface RegenerateSitemapsResult {
  outputDir: string;
  routesPerLanguage: number;
  files: string[];
}

/**
 * MINIMAL — see module docstring. Writes `sitemap-en.xml`,
 * `sitemap-kn.xml`, and a `sitemap.xml` index into `outputDir`, which
 * defaults to the repo's `public/` directory — the same directory
 * Astro's own static assets are served from, so these land wherever the
 * running deployment already serves `/robots.txt`-adjacent static files
 * from.
 */
export function regenerateSitemaps(outputDir: string = path.join(process.cwd(), 'public')): RegenerateSitemapsResult {
  mkdirSync(outputDir, { recursive: true });

  const lastmod = new Date().toISOString();

  writeFileSync(path.join(outputDir, 'sitemap-en.xml'), buildUrlSet('en', lastmod), 'utf-8');
  writeFileSync(path.join(outputDir, 'sitemap-kn.xml'), buildUrlSet('kn', lastmod), 'utf-8');
  writeFileSync(path.join(outputDir, 'sitemap.xml'), buildSitemapIndex(lastmod), 'utf-8');

  return {
    outputDir,
    routesPerLanguage: STATIC_ROUTES.length,
    files: ['sitemap.xml', 'sitemap-en.xml', 'sitemap-kn.xml'],
  };
}
