import { describe, it, expect } from 'vitest';
import { getPageContent } from '../../src/i18n/content';

const ALL_SLUGS = [
  'about',
  'about-election',
  'check-registration',
  'voting-guide',
  'voter-id',
  'how-to-vote',
  'find-booth',
  'terms',
  'privacy',
  'partner-with-us',
  'press',
  'home-intro',
];

describe('getPageContent()', () => {
  it('returns an entry with a non-empty title for a known EN slug', () => {
    const entry = getPageContent('en', 'about');
    expect(entry).not.toBeNull();
    expect(entry?.title).toBeTruthy();
    expect(typeof entry?.title).toBe('string');
  });

  it('resolves all 12 EN slugs', () => {
    for (const slug of ALL_SLUGS) {
      const entry = getPageContent('en', slug);
      expect(entry, `expected an EN entry for slug "${slug}"`).not.toBeNull();
      expect(entry?.title).toBeTruthy();
      expect(entry?.description).toBeTruthy();
      expect(entry?.body.length ?? 0).toBeGreaterThan(0);
    }
  });

  it('resolves a genuine KN entry now that Task 9 has generated content/pages/kn/*.md', () => {
    const en = getPageContent('en', 'about');
    const kn = getPageContent('kn', 'about');
    expect(kn).not.toBeNull();
    expect(kn?.lang).toBe('kn');
    expect(kn?.fallback).toBe(false);
    expect(kn?.title).toBeTruthy();
    // The KN title is a genuine translation, not a copy of the EN title.
    expect(kn?.title).not.toBe(en?.title);
  });

  it('resolves all 12 KN slugs generated by Task 9, none as a fallback', () => {
    for (const slug of ALL_SLUGS) {
      const entry = getPageContent('kn', slug);
      expect(entry, `expected a KN entry for slug "${slug}"`).not.toBeNull();
      expect(entry?.lang, `slug "${slug}"`).toBe('kn');
      expect(entry?.fallback, `slug "${slug}"`).toBe(false);
      expect(entry?.title).toBeTruthy();
      expect(entry?.description).toBeTruthy();
      expect(entry?.body.length ?? 0).toBeGreaterThan(0);
    }
  });

  it('returns null for an unknown slug', () => {
    expect(getPageContent('en', 'no-such-page')).toBeNull();
    expect(getPageContent('kn', 'no-such-page')).toBeNull();
  });

  it('marks a genuine EN entry as not a fallback', () => {
    const entry = getPageContent('en', 'about');
    expect(entry?.fallback).toBe(false);
  });
});
